name: Deploy para Hostinger

on:
  push:
    branches:
      - master  # ou 'main', dependendo da sua branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar c贸digo do reposit贸rio
        uses: actions/checkout@v3

      - name: Configurar FTP e enviar arquivos
        uses: sebastienvercammen/ftp-deploy-action@v1.0.0  # Nova alternativa
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Diret贸rio local a ser enviado
          server-dir: /public_html/  # Diret贸rio no servidor (geralmente 'public_html')
